siteName: Seven Skills Tutoring
title: Seven Skills Tutoring
author: David White
url: https://github.com/webdigga/michael-carragher-tutor
poweredBy: Seven Kings Web Design
description: Michael Carragher, a Tutor in South West London
type: website
logoAlt: Seven Skills Tutoring logo
logoUrl: /static/img/logo.png
