siteName: Seven Skills Tutoring
title: Seven Skills Tutoring
author: David White
url: https://github.com/webdigga/michael-carragher-tutor
poweredBy: Kabooly
poweredByUrl: https://kabooly.com/
type: website
logoAlt: Seven Skills Tutoring Owl logo
logoUrl: /_includes/static/img/logo.png
email: michael@sevenskillstutoring.com
phone: "07311 391185"
addressLineOne: Carisbrooke House
addressLineTwo: Royal Quarter
addressLineThree: Seven Kings Way
townCity: Kingston upon Thames
country: GB
region: London
postCode: KT2 5BS
openingWeekday: "09:00"
closingWeekday: "20:00"
openingSaturday: "09:00"
closingSaturday: "14:00"
