siteName: Divorce Coaching
title: Divorce Coaching
author: David White
url: https://github.com/webdigga/divorce-coach
poweredBy: Arragon Affiliates
description: A rewarding career in divorce coaching to fit around your lifestyle
type: website
logoAlt: Seven Kings Web Design Logo
logoUrl: /static/img/logo.png
