siteName: Seven Kings Web Design
title: Seven Kings Web Design
author: David White
url: https://github.com/webdigga/seven-kings
poweredBy: Seven Kings Web Design
description: Kingston Upon Thames based web design company
type: website
logoAlt: Moulded Ear Plugs logo
logoUrl: /static/img/website_logo.webp
