siteName: 7 Skills tutoring
title: 7 Skills tutoring
author: David White
url: https://github.com/webdigga/michael-carragher-tutor
poweredBy: Seven Kings Web Design
description: Michael Carragher, a Tutor in South West London
type: website
logoAlt: 7 Skills tutoring logo
logoUrl: /static/img/logo.png
