backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: main
  ### enable below lines for github integration ###
  # name: github
  # repo: https://github.com/webdigga/ear-protectors
media_folder: "src/_includes/static/img"
public_folder: "/_includes/static/img"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - label: "Article"
    name: "articles"
    folder: "src/articles"
    create: true
    editor:
      preview: false
    fields:
      - {
        label: "Title",
        name: "title",
        widget: "string",
        hint: "*This title will be used in the page's H1 tag, and also determines the URL (between 20 and 70 characters). If you want to make changes to this section after the page has been published then it's best to chat to David first.*",
        pattern: ['^.{20,70}$', "Must be between 20 and 70 characters"]
      }
      - { 
        label: "SEO Title",
        name: "seoTitle",
        widget: "string",
        hint: "*This title will be used in the title tag for search engines (between 50 and 60 characters). If you want to make changes to this section after the page has been published then it's best to chat to David first.*",
        pattern: ['^.{50,60}$', "Must be between 50 and 60 characters"]
      }
      - {
        label: "Description",
        name: "description",
        widget: "string",
        hint: "*Used in search engines (between 70 and 155 characters). If you want to make changes to this section after the page has been published then it's best to chat to David first.*",
        pattern: ['^.{70,155}$', "Must be between 70 and 155 characters"]
      }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - widget: select
        label: "type"
        name: "type"
        create: true
        options: ["article", "privacy"]
        default: "article"
      - widget: select
        label: "tags"
        name: "tags"
        multiple: true
        create: true
        options: ["article", "privacy", "report", "faq"]
        default: ["article"]
  - label: "Homepage Text"
    name: "homepageSpiel"
    folder: "src/homepageSpiel"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "markdown" }
  - label: "Page Specific SEO"
    name: "pages"
    editor:
      preview: false
    files:
      - label: "Homepage"
        name: "homepage"
        file: "src/_data/homepagePageSeo.yaml"
        fields:
          - { 
            label: "SEO Title",
            name: "seoTitle",
            widget: "string",
            hint: "*This title will be used in the title tag for search engines (between 50 and 60 characters). If you want to make changes to this section after the page has been published then it's best to chat to David first.*",
            pattern: ['^.{50,60}$', "Must be between 50 and 60 characters"]
          }
          - {
            label: "Description",
            name: "description",
            widget: "string",
            hint: "*Used in search engines (between 70 and 155 characters). If you want to make changes to this section after the page has been published then it's best to chat to David first.*",
            pattern: ['^.{70,155}$', "Must be between 70 and 155 characters"]
          }
      - label: "Contact"
        name: "contact"
        file: "src/_data/contactPageSeo.yaml"
        fields:
          - { 
            label: "SEO Title",
            name: "seoTitle",
            widget: "string",
            hint: "*This title will be used in the title tag for search engines (between 50 and 60 characters). If you want to make changes to this section after the page has been published then it's best to chat to David first.*",
            pattern: ['^.{50,60}$', "Must be between 50 and 60 characters"]
          }
          - {
            label: "Description",
            name: "description",
            widget: "string",
            hint: "*Used in search engines (between 70 and 155 characters). If you want to make changes to this section after the page has been published then it's best to chat to David first.*",
            pattern: ['^.{70,155}$', "Must be between 70 and 155 characters"]
          }
  - label: "Settings"
    name: "settings"
    editor:
      preview: false
    files:
      - label: "Navigation"
        name: "items"
        file: "src/_data/navigation.yaml"
        fields:
          - label: Nav Items
            name: firstLevelItems
            widget: list
            collapsed: false
            allow_add: false
            fields:
              - { label: Title, name: text, widget: string }
              - { label: URL, name: url, widget: string }
              - label: Nav Items
                name: secondLevelItems
                widget: list
                collapsed: true
                fields:
                  - { label: Title, name: text, widget: string }
                  - { label: URL, name: url, widget: string }
      - label: "Meta Settings"
        name: "settings"
        file: "src/_data/settings.yaml"
        fields:
          - { label: Site Name, name: siteName, widget: string }
          - { label: Title, name: title, widget: string }
          - { label: Author, name: author, widget: string }
          - { label: URL, name: url, widget: string }
          - { label: Powered by, name: poweredBy, widget: string }
          - { label: Powered by link, name: poweredByUrl, widget: string }
          - { label: Type (type of template), name: type, widget: string }
          - { label: Logo (Alt), name: logoAlt, widget: string }
          - { label: Email, name: email, widget: string }
          - { label: Phone, name: phone, widget: string }
          - { label: Address Line One, name: addressLineOne, widget: string }
          - { label: Address Line Two, name: addressLineTwo, widget: string }
          - { label: Address Line Three, name: addressLineThree, widget: string }
          - { label: Town/City, name: townCity, widget: string }
          - { label: Country, name: country, widget: string }
          - { label: Region, name: region, widget: string }
          - { label: Post Code, name: postCode, widget: string }
          - { label: Opening Weekday, name: openingWeekday, widget: string }
          - { label: Closing Weekday, name: closingWeekday, widget: string }
          - { label: Opening Saturday, name: openingSaturday, widget: string }
          - { label: Closing Saturday, name: closingSaturday, widget: string }
          - label: "Logo (URL)"
            name: "logoUrl"
            widget: "image"
            choose_url: true
            media_library:
              config:
                multiple: false
  - label: "Components"
    name: "components"
    editor:
      preview: false
    files:
      - label: "Testimonials"
        name: "testimonials"
        file: "src/_data/testimonials.yaml"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Sub Title, name: subTitle, widget: text }
          - label: Testimonial Items
            name: testimonialItems
            widget: list
            collapsed: false
            allow_add: false
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Quote, name: quote, widget: string }
              - { label: Name, name: name, widget: string }